// Test generated by RoostGPT for test gs-messaging-jms using AI Model gpt

package hello;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Email_getToc172459cf2Test {
    private Email email;

    @BeforeEach
    public void setUp() {
        email = new Email();
    }

    @Test
    public void testGetTo_Success() {
        String expectedTo = "test@example.com";
        email.setTo(expectedTo);
        String actualTo = email.getTo();
        assertEquals(expectedTo, actualTo, "Email 'to' field should match the set value");
    }

    @Test
    public void testGetTo_Null() {
        String actualTo = email.getTo();
        assertEquals(null, actualTo, "Email 'to' field should be null if not set");
    }
}
