// Test generated by RoostGPT for test gs-messaging-jms using AI Model gpt

package hello;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

public class Email_Email347e54534eTest {

    @Test
    public void testEmailConstructor() {
        Email email = new Email();
        assertNotNull(email, "Email object should not be null");
    }
}
