// Test generated by RoostGPT for test gs-messaging-jms using AI Model gpt

package hello;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.jms.core.JmsTemplate;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.times;
import static org.mockito.ArgumentMatchers.any;

@RunWith(MockitoJUnitRunner.class)
public class Receiver_receiveMessage955141981dTest {

    @InjectMocks
    private Receiver receiver;

    @Mock
    private JmsTemplate jmsTemplate;

    @Mock
    private Email email;

    @Before
    public void setUp() {
        // TODO: Initialize email with appropriate values
    }

    @Test
    public void testReceiveMessageSuccess() {
        receiver.receiveMessage(email);
        verify(jmsTemplate, times(1)).convertAndSend(any(String.class), any(Email.class));
    }

    @Test(expected = RuntimeException.class)
    public void testReceiveMessageFailure() {
        // TODO: Setup scenario for failure
        receiver.receiveMessage(email);
    }
}
